#version: '3'
networks:
  localhost:
    name: localhost
    driver: bridge

services:
  auth-vivelibre:
    image: skeet15/auth-vivelibre
    container_name: auth-vivelibre
    stdin_open: true
    tty: true
    ports:
      - "8080:8080" # External:Internal
    networks:
      - localhost

  test-atam-token:
    image: fdbozzo/test-atam-token:latest
    container_name: test-atam-token
    stdin_open: true
    tty: true
    depends_on:
      - auth-vivelibre
    ports:
      - "8081:8081" # External:Internal
    networks:
      - localhost
